import 'package:flutter/foundation.dart';
import 'package:hcms_revived2/models/localdbmodel/localdbmodel.dart';
import '../../helpers/dbhelper.dart';

import 'package:intl/intl.dart';

class SeedlingMonitoring2Provider extends ChangeNotifier {
  static var newdate = DateTime.now();
  static var formatDate = DateFormat('MMM d, y');
  String formattedDat = formatDate.format(newdate);

  List<SeedlingMonitoring2> _smLists = [];

  List<SeedlingMonitoring2> get smLists {
    return [..._smLists];
  }

  SeedlingMonitoring2 findById(String id) {
    return _smLists.firstWhere((monitoring) => monitoring.smId == id);
  }

  void addSeedlingMonitoring2(
    String pickedsmCommunity,
    String pickedsmVisitDate,
    String pickedsmEnumeratorValue,
    String pickedsmBaseline,
    String pickedsurveyorName,
    String pickeddateOfSurvey,
    String pickedcommunity,
    String pickedfarmerName,
    String pickedfarmerIDNumber,
    String pickedtypeOfPlantation,
    String pickedtotalSizeAcres,
    String pickedspeciesProvidedPlanted,
    String pickedpr_quantityReceived,
    String pickedpr_quantityPlanted,
    String pickedpr_farmerdOB,
    String pickedka_quantityReceived,
    String pickedka_quantityPlanted,
    String pickedka_farmerdOB,
    String pickedda_quantityReceived,
    String pickedda_quantityPlanted,
    String pickedda_farmerdOB,
    String pickeded_quantityReceived,
    String pickeded_quantityPlanted,
    String pickeded_farmerdOB,
    String pickedem_quantityReceived,
    String pickedem_quantityPlanted,
    String pickedem_farmerdOB,
    String pickedof_quantityReceived,
    String pickedof_quantityPlanted,
    String pickedof_farmerdOB,
    String pickedmd_quantityReceived,
    String pickedmd_quantityPlanted,
    String pickedmd_farmerdOB,
    String pickedmo_quantityReceived,
    String pickedmo_quantityPlanted,
    String pickedmo_farmerdOB,
    String pickedok_quantityReceived,
    String pickedok_quantityPlanted,
    String pickedok_farmerdOB,
    String pickedeu_quantityReceived,
    String pickedeu_quantityPlanted,
    String pickedeu_farmerdOB,
    String pickedba_quantityReceived,
    String pickedba_quantityPlanted,
    String pickedba_farmerdOB,
    String pickedmappedFarmBoundaries,
    String pickedtotalSeedlingsAliveController,
    String pickedspeciesAlive,
    String pickedreasonForDeath,
    String pickedmappedSurvidedSeedlings,
    String pickedsourceOfWater,
    String pickedwaterignFrequency,
    String pickedanyExtremeSigns,
    String pickedextremeWeathers,
    String pickedpestsAroundYesNoValue,
    String pickedpestDescription,
    String pickedsignsDiseaseYesNoValue,
    String pickeddiseaseDescription,
    String pickedfertiliserAppliedYesNoValue,
    String pickedfertiliserType,
    String pickedpesticideHerbicideAppliedYesNoValue,
    String pickedpesticideHerbicideType,
    String pickedadditionalObservations,

    // connection Status
    String pickedconStat,
  ) {
    final newSeedlingMonitoring2 = SeedlingMonitoring2(
      smId: DateTime.now().toString(),
      smTimeDisplay: formattedDat,
      smCommunity: pickedsmCommunity,
      smVisitDate: pickedsmVisitDate,
      smEnumeratorValue: pickedsmEnumeratorValue,
      smBaseline: pickedsmBaseline,
      surveyorName: pickedsurveyorName,
      dateOfSurvey: pickeddateOfSurvey,
      community: pickedcommunity,
      farmerName: pickedfarmerName,
      farmerIDNumber: pickedfarmerIDNumber,
      typeOfPlantation: pickedtypeOfPlantation,
      totalSizeAcres: pickedtotalSizeAcres,
      speciesProvidedPlanted: pickedspeciesProvidedPlanted,
      pr_quantityReceived: pickedpr_quantityReceived,
      pr_quantityPlanted: pickedpr_quantityPlanted,
      pr_farmerdOB: pickedpr_farmerdOB,
      ka_quantityReceived: pickedka_quantityReceived,
      ka_quantityPlanted: pickedka_quantityPlanted,
      ka_farmerdOB: pickedka_farmerdOB,
      da_quantityReceived: pickedda_quantityReceived,
      da_quantityPlanted: pickedda_quantityPlanted,
      da_farmerdOB: pickedda_farmerdOB,
      ed_quantityReceived: pickeded_quantityReceived,
      ed_quantityPlanted: pickeded_quantityPlanted,
      ed_farmerdOB: pickeded_farmerdOB,
      em_quantityReceived: pickedem_quantityReceived,
      em_quantityPlanted: pickedem_quantityPlanted,
      em_farmerdOB: pickedem_farmerdOB,
      of_quantityReceived: pickedof_quantityReceived,
      of_quantityPlanted: pickedof_quantityPlanted,
      of_farmerdOB: pickedof_farmerdOB,
      md_quantityReceived: pickedmd_quantityReceived,
      md_quantityPlanted: pickedmd_quantityPlanted,
      md_farmerdOB: pickedmd_farmerdOB,
      mo_quantityReceived: pickedmo_quantityReceived,
      mo_quantityPlanted: pickedmo_quantityPlanted,
      mo_farmerdOB: pickedmo_farmerdOB,
      ok_quantityReceived: pickedok_quantityReceived,
      ok_quantityPlanted: pickedok_quantityPlanted,
      ok_farmerdOB: pickedok_farmerdOB,
      eu_quantityReceived: pickedeu_quantityReceived,
      eu_quantityPlanted: pickedeu_quantityPlanted,
      eu_farmerdOB: pickedeu_farmerdOB,
      ba_quantityReceived: pickedba_quantityReceived,
      ba_quantityPlanted: pickedba_quantityPlanted,
      ba_farmerdOB: pickedba_farmerdOB,
      mappedFarmBoundaries: pickedmappedFarmBoundaries,
      totalSeedlingsAliveController: pickedtotalSeedlingsAliveController,
      speciesAlive: pickedspeciesAlive,
      reasonForDeath: pickedreasonForDeath,
      mappedSurvidedSeedlings: pickedmappedSurvidedSeedlings,
      sourceOfWater: pickedsourceOfWater,
      waterignFrequency: pickedwaterignFrequency,
      anyExtremeSigns: pickedanyExtremeSigns,
      extremeWeathers: pickedextremeWeathers,
      pestsAroundYesNoValue: pickedpestsAroundYesNoValue,
      pestDescription: pickedpestDescription,
      signsDiseaseYesNoValue: pickedsignsDiseaseYesNoValue,
      diseaseDescription: pickeddiseaseDescription,
      fertiliserAppliedYesNoValue: pickedfertiliserAppliedYesNoValue,
      fertiliserType: pickedfertiliserType,
      pesticideHerbicideAppliedYesNoValue:
          pickedpesticideHerbicideAppliedYesNoValue,
      pesticideHerbicideType: pickedpesticideHerbicideType,
      additionalObservations: pickedadditionalObservations,
      conStat: pickedconStat,
    );
    _smLists.add(newSeedlingMonitoring2);
    // _smLists.insert(0, newSeedlingMonitoring2);
    notifyListeners();

    DBHelper.insert('seedling_monitoring2', {
      'id': newSeedlingMonitoring2.smId,
      'smTimeDisplay': newSeedlingMonitoring2.smTimeDisplay,
      'smCommunity': newSeedlingMonitoring2.smCommunity,
      'smVisitDate': newSeedlingMonitoring2.smVisitDate,
      'smEnumeratorValue': newSeedlingMonitoring2.smEnumeratorValue,
      'smBaseline': newSeedlingMonitoring2.smBaseline,
      'surveyorName': newSeedlingMonitoring2.surveyorName,
      'dateOfSurvey': newSeedlingMonitoring2.dateOfSurvey,
      'community': newSeedlingMonitoring2.community,
      'farmerName': newSeedlingMonitoring2.farmerName,
      'farmerIDNumber': newSeedlingMonitoring2.farmerIDNumber,
      'typeOfPlantation': newSeedlingMonitoring2.typeOfPlantation,
      'totalSizeAcres': newSeedlingMonitoring2.totalSizeAcres,
      'speciesProvidedPlanted': newSeedlingMonitoring2.speciesProvidedPlanted,
      'pr_quantityReceived': newSeedlingMonitoring2.pr_quantityReceived,
      'pr_quantityPlanted': newSeedlingMonitoring2.pr_quantityPlanted,
      'pr_farmerdOB': newSeedlingMonitoring2.pr_farmerdOB,
      'ka_quantityReceived': newSeedlingMonitoring2.ka_quantityReceived,
      'ka_quantityPlanted': newSeedlingMonitoring2.ka_quantityPlanted,
      'ka_farmerdOB': newSeedlingMonitoring2.ka_farmerdOB,
      'da_quantityReceived': newSeedlingMonitoring2.da_quantityReceived,
      'da_quantityPlanted': newSeedlingMonitoring2.da_quantityPlanted,
      'da_farmerdOB': newSeedlingMonitoring2.da_farmerdOB,
      'ed_quantityReceived': newSeedlingMonitoring2.ed_quantityReceived,
      'ed_quantityPlanted': newSeedlingMonitoring2.ed_quantityPlanted,
      'ed_farmerdOB': newSeedlingMonitoring2.ed_farmerdOB,
      'em_quantityReceived': newSeedlingMonitoring2.em_quantityReceived,
      'em_quantityPlanted': newSeedlingMonitoring2.em_quantityPlanted,
      'em_farmerdOB': newSeedlingMonitoring2.em_farmerdOB,
      'of_quantityReceived': newSeedlingMonitoring2.of_quantityReceived,
      'of_quantityPlanted': newSeedlingMonitoring2.of_quantityPlanted,
      'of_farmerdOB': newSeedlingMonitoring2.of_farmerdOB,
      'md_quantityReceived': newSeedlingMonitoring2.md_quantityReceived,
      'md_quantityPlanted': newSeedlingMonitoring2.md_quantityPlanted,
      'md_farmerdOB': newSeedlingMonitoring2.md_farmerdOB,
      'mo_quantityReceived': newSeedlingMonitoring2.mo_quantityReceived,
      'mo_quantityPlanted': newSeedlingMonitoring2.mo_quantityPlanted,
      'mo_farmerdOB': newSeedlingMonitoring2.mo_farmerdOB,
      'ok_quantityReceived': newSeedlingMonitoring2.ok_quantityReceived,
      'ok_quantityPlanted': newSeedlingMonitoring2.ok_quantityPlanted,
      'ok_farmerdOB': newSeedlingMonitoring2.ok_farmerdOB,
      'eu_quantityReceived': newSeedlingMonitoring2.eu_quantityReceived,
      'eu_quantityPlanted': newSeedlingMonitoring2.eu_quantityPlanted,
      'eu_farmerdOB': newSeedlingMonitoring2.eu_farmerdOB,
      'ba_quantityReceived': newSeedlingMonitoring2.ba_quantityReceived,
      'ba_quantityPlanted': newSeedlingMonitoring2.ba_quantityPlanted,
      'ba_farmerdOB': newSeedlingMonitoring2.ba_farmerdOB,
      'mappedFarmBoundaries': newSeedlingMonitoring2.mappedFarmBoundaries,
      'totalSeedlingsAliveController':
          newSeedlingMonitoring2.totalSeedlingsAliveController,
      'speciesAlive': newSeedlingMonitoring2.speciesAlive,
      'reasonForDeath': newSeedlingMonitoring2.reasonForDeath,
      'mappedSurvidedSeedlings': newSeedlingMonitoring2.mappedSurvidedSeedlings,
      'sourceOfWater': newSeedlingMonitoring2.sourceOfWater,
      'waterignFrequency': newSeedlingMonitoring2.waterignFrequency,
      'anyExtremeSigns': newSeedlingMonitoring2.anyExtremeSigns,
      'extremeWeathers': newSeedlingMonitoring2.extremeWeathers,
      'pestsAroundYesNoValue': newSeedlingMonitoring2.pestsAroundYesNoValue,
      'pestDescription': newSeedlingMonitoring2.pestDescription,
      'signsDiseaseYesNoValue': newSeedlingMonitoring2.signsDiseaseYesNoValue,
      'diseaseDescription': newSeedlingMonitoring2.diseaseDescription,
      'fertiliserAppliedYesNoValue':
          newSeedlingMonitoring2.fertiliserAppliedYesNoValue,
      'fertiliserType': newSeedlingMonitoring2.fertiliserType,
      'pesticideHerbicideAppliedYesNoValue':
          newSeedlingMonitoring2.pesticideHerbicideAppliedYesNoValue,
      'pesticideHerbicideType': newSeedlingMonitoring2.pesticideHerbicideType,
      'additionalObservations': newSeedlingMonitoring2.additionalObservations,
      'conStat': newSeedlingMonitoring2.conStat,
    });
  }

  Future<void> fetchAndSetSeedlingMonitoring2() async {
    final dataList = await DBHelper.fetchData('seedling_monitoring2');
    _smLists = dataList
        .map((smLists) => SeedlingMonitoring2(
              smId: smLists['id'],
              smTimeDisplay: smLists['smTimeDisplay'],
              smCommunity: smLists['smCommunity'],
              smVisitDate: smLists['smVisitDate'],
              smEnumeratorValue: smLists['smEnumeratorValue'],
              smBaseline: smLists['smBaseline'],
              surveyorName: smLists['surveyorName'],
              dateOfSurvey: smLists['dateOfSurvey'],
              community: smLists['community'],
              farmerName: smLists['farmerName'],
              farmerIDNumber: smLists['farmerIDNumber'],
              typeOfPlantation: smLists['typeOfPlantation'],
              totalSizeAcres: smLists['totalSizeAcres'],
              speciesProvidedPlanted: smLists['speciesProvidedPlanted'],
              pr_quantityReceived: smLists['pr_quantityReceived'],
              pr_quantityPlanted: smLists['pr_quantityPlanted'],
              pr_farmerdOB: smLists['pr_farmerdOB'],
              ka_quantityReceived: smLists['ka_quantityReceived'],
              ka_quantityPlanted: smLists['ka_quantityPlanted'],
              ka_farmerdOB: smLists['ka_farmerdOB'],
              da_quantityReceived: smLists['da_quantityReceived'],
              da_quantityPlanted: smLists['da_quantityPlanted'],
              da_farmerdOB: smLists['da_farmerdOB'],
              ed_quantityReceived: smLists['ed_quantityReceived'],
              ed_quantityPlanted: smLists['ed_quantityPlanted'],
              ed_farmerdOB: smLists['ed_farmerdOB'],
              em_quantityReceived: smLists['em_quantityReceived'],
              em_quantityPlanted: smLists['em_quantityPlanted'],
              em_farmerdOB: smLists['em_farmerdOB'],
              of_quantityReceived: smLists['of_quantityReceived'],
              of_quantityPlanted: smLists['of_quantityPlanted'],
              of_farmerdOB: smLists['of_farmerdOB'],
              md_quantityReceived: smLists['md_quantityReceived'],
              md_quantityPlanted: smLists['md_quantityPlanted'],
              md_farmerdOB: smLists['md_farmerdOB'],
              mo_quantityReceived: smLists['mo_quantityReceived'],
              mo_quantityPlanted: smLists['mo_quantityPlanted'],
              mo_farmerdOB: smLists['mo_farmerdOB'],
              ok_quantityReceived: smLists['ok_quantityReceived'],
              ok_quantityPlanted: smLists['ok_quantityPlanted'],
              ok_farmerdOB: smLists['ok_farmerdOB'],
              eu_quantityReceived: smLists['eu_quantityReceived'],
              eu_quantityPlanted: smLists['eu_quantityPlanted'],
              eu_farmerdOB: smLists['eu_farmerdOB'],
              ba_quantityReceived: smLists['ba_quantityReceived'],
              ba_quantityPlanted: smLists['ba_quantityPlanted'],
              ba_farmerdOB: smLists['ba_farmerdOB'],
              mappedFarmBoundaries: smLists['mappedFarmBoundaries'],
              totalSeedlingsAliveController:
                  smLists['totalSeedlingsAliveController'],
              speciesAlive: smLists['speciesAlive'],
              reasonForDeath: smLists['reasonForDeath'],
              mappedSurvidedSeedlings: smLists['mappedSurvidedSeedlings'],
              sourceOfWater: smLists['sourceOfWater'],
              waterignFrequency: smLists['waterignFrequency'],
              anyExtremeSigns: smLists['anyExtremeSigns'],
              extremeWeathers: smLists['extremeWeathers'],
              pestsAroundYesNoValue: smLists['pestsAroundYesNoValue'],
              pestDescription: smLists['pestDescription'],
              signsDiseaseYesNoValue: smLists['signsDiseaseYesNoValue'],
              diseaseDescription: smLists['diseaseDescription'],
              fertiliserAppliedYesNoValue:
                  smLists['fertiliserAppliedYesNoValue'],
              fertiliserType: smLists['fertiliserType'],
              pesticideHerbicideAppliedYesNoValue:
                  smLists['pesticideHerbicideAppliedYesNoValue'],
              pesticideHerbicideType: smLists['pesticideHerbicideType'],
              additionalObservations: smLists['additionalObservations'],
              conStat: smLists['conStat'],
            ))
        .toList();
    notifyListeners();
  }

  Future<void> fetchAndSetSeedlingMonitoring2ByFieldName(String? fieldname) async {
    final dataList =
        await DBHelper.fetchData2('seedling_monitoring2', fieldname);
    _smLists = dataList
        .map((smLists) => SeedlingMonitoring2(
              smId: smLists['id'],
              smTimeDisplay: smLists['smTimeDisplay'],
              smCommunity: smLists['smCommunity'],
              smVisitDate: smLists['smVisitDate'],
              smEnumeratorValue: smLists['smEnumeratorValue'],
              smBaseline: smLists['smBaseline'],
              surveyorName: smLists['surveyorName'],
              dateOfSurvey: smLists['dateOfSurvey'],
              community: smLists['community'],
              farmerName: smLists['farmerName'],
              farmerIDNumber: smLists['farmerIDNumber'],
              typeOfPlantation: smLists['typeOfPlantation'],
              totalSizeAcres: smLists['totalSizeAcres'],
              speciesProvidedPlanted: smLists['speciesProvidedPlanted'],
              pr_quantityReceived: smLists['pr_quantityReceived'],
              pr_quantityPlanted: smLists['pr_quantityPlanted'],
              pr_farmerdOB: smLists['pr_farmerdOB'],
              ka_quantityReceived: smLists['ka_quantityReceived'],
              ka_quantityPlanted: smLists['ka_quantityPlanted'],
              ka_farmerdOB: smLists['ka_farmerdOB'],
              da_quantityReceived: smLists['da_quantityReceived'],
              da_quantityPlanted: smLists['da_quantityPlanted'],
              da_farmerdOB: smLists['da_farmerdOB'],
              ed_quantityReceived: smLists['ed_quantityReceived'],
              ed_quantityPlanted: smLists['ed_quantityPlanted'],
              ed_farmerdOB: smLists['ed_farmerdOB'],
              em_quantityReceived: smLists['em_quantityReceived'],
              em_quantityPlanted: smLists['em_quantityPlanted'],
              em_farmerdOB: smLists['em_farmerdOB'],
              of_quantityReceived: smLists['of_quantityReceived'],
              of_quantityPlanted: smLists['of_quantityPlanted'],
              of_farmerdOB: smLists['of_farmerdOB'],
              md_quantityReceived: smLists['md_quantityReceived'],
              md_quantityPlanted: smLists['md_quantityPlanted'],
              md_farmerdOB: smLists['md_farmerdOB'],
              mo_quantityReceived: smLists['mo_quantityReceived'],
              mo_quantityPlanted: smLists['mo_quantityPlanted'],
              mo_farmerdOB: smLists['mo_farmerdOB'],
              ok_quantityReceived: smLists['ok_quantityReceived'],
              ok_quantityPlanted: smLists['ok_quantityPlanted'],
              ok_farmerdOB: smLists['ok_farmerdOB'],
              eu_quantityReceived: smLists['eu_quantityReceived'],
              eu_quantityPlanted: smLists['eu_quantityPlanted'],
              eu_farmerdOB: smLists['eu_farmerdOB'],
              ba_quantityReceived: smLists['ba_quantityReceived'],
              ba_quantityPlanted: smLists['ba_quantityPlanted'],
              ba_farmerdOB: smLists['ba_farmerdOB'],
              mappedFarmBoundaries: smLists['mappedFarmBoundaries'],
              totalSeedlingsAliveController:
                  smLists['totalSeedlingsAliveController'],
              speciesAlive: smLists['speciesAlive'],
              reasonForDeath: smLists['reasonForDeath'],
              mappedSurvidedSeedlings: smLists['mappedSurvidedSeedlings'],
              sourceOfWater: smLists['sourceOfWater'],
              waterignFrequency: smLists['waterignFrequency'],
              anyExtremeSigns: smLists['anyExtremeSigns'],
              extremeWeathers: smLists['extremeWeathers'],
              pestsAroundYesNoValue: smLists['pestsAroundYesNoValue'],
              pestDescription: smLists['pestDescription'],
              signsDiseaseYesNoValue: smLists['signsDiseaseYesNoValue'],
              diseaseDescription: smLists['diseaseDescription'],
              fertiliserAppliedYesNoValue:
                  smLists['fertiliserAppliedYesNoValue'],
              fertiliserType: smLists['fertiliserType'],
              pesticideHerbicideAppliedYesNoValue:
                  smLists['pesticideHerbicideAppliedYesNoValue'],
              pesticideHerbicideType: smLists['pesticideHerbicideType'],
              additionalObservations: smLists['additionalObservations'],
              conStat: smLists['conStat'],
            ))
        .toList();
    notifyListeners();
  }

  Future<void> fetchAndSetSeedlingMonitoring2Where(
      String? fieldname, String? dateFactor) async {
    final dataList = await DBHelper.fetchDataWhere(
        'seedling_monitoring2', fieldname, dateFactor);
    _smLists = dataList
        .map((smLists) => SeedlingMonitoring2(
              smId: smLists['id'],
              smTimeDisplay: smLists['smTimeDisplay'],
              smCommunity: smLists['smCommunity'],
              smVisitDate: smLists['smVisitDate'],
              smEnumeratorValue: smLists['smEnumeratorValue'],
              smBaseline: smLists['smBaseline'],
              surveyorName: smLists['surveyorName'],
              dateOfSurvey: smLists['dateOfSurvey'],
              community: smLists['community'],
              farmerName: smLists['farmerName'],
              farmerIDNumber: smLists['farmerIDNumber'],
              typeOfPlantation: smLists['typeOfPlantation'],
              totalSizeAcres: smLists['totalSizeAcres'],
              speciesProvidedPlanted: smLists['speciesProvidedPlanted'],
              pr_quantityReceived: smLists['pr_quantityReceived'],
              pr_quantityPlanted: smLists['pr_quantityPlanted'],
              pr_farmerdOB: smLists['pr_farmerdOB'],
              ka_quantityReceived: smLists['ka_quantityReceived'],
              ka_quantityPlanted: smLists['ka_quantityPlanted'],
              ka_farmerdOB: smLists['ka_farmerdOB'],
              da_quantityReceived: smLists['da_quantityReceived'],
              da_quantityPlanted: smLists['da_quantityPlanted'],
              da_farmerdOB: smLists['da_farmerdOB'],
              ed_quantityReceived: smLists['ed_quantityReceived'],
              ed_quantityPlanted: smLists['ed_quantityPlanted'],
              ed_farmerdOB: smLists['ed_farmerdOB'],
              em_quantityReceived: smLists['em_quantityReceived'],
              em_quantityPlanted: smLists['em_quantityPlanted'],
              em_farmerdOB: smLists['em_farmerdOB'],
              of_quantityReceived: smLists['of_quantityReceived'],
              of_quantityPlanted: smLists['of_quantityPlanted'],
              of_farmerdOB: smLists['of_farmerdOB'],
              md_quantityReceived: smLists['md_quantityReceived'],
              md_quantityPlanted: smLists['md_quantityPlanted'],
              md_farmerdOB: smLists['md_farmerdOB'],
              mo_quantityReceived: smLists['mo_quantityReceived'],
              mo_quantityPlanted: smLists['mo_quantityPlanted'],
              mo_farmerdOB: smLists['mo_farmerdOB'],
              ok_quantityReceived: smLists['ok_quantityReceived'],
              ok_quantityPlanted: smLists['ok_quantityPlanted'],
              ok_farmerdOB: smLists['ok_farmerdOB'],
              eu_quantityReceived: smLists['eu_quantityReceived'],
              eu_quantityPlanted: smLists['eu_quantityPlanted'],
              eu_farmerdOB: smLists['eu_farmerdOB'],
              ba_quantityReceived: smLists['ba_quantityReceived'],
              ba_quantityPlanted: smLists['ba_quantityPlanted'],
              ba_farmerdOB: smLists['ba_farmerdOB'],
              mappedFarmBoundaries: smLists['mappedFarmBoundaries'],
              totalSeedlingsAliveController:
                  smLists['totalSeedlingsAliveController'],
              speciesAlive: smLists['speciesAlive'],
              reasonForDeath: smLists['reasonForDeath'],
              mappedSurvidedSeedlings: smLists['mappedSurvidedSeedlings'],
              sourceOfWater: smLists['sourceOfWater'],
              waterignFrequency: smLists['waterignFrequency'],
              anyExtremeSigns: smLists['anyExtremeSigns'],
              extremeWeathers: smLists['extremeWeathers'],
              pestsAroundYesNoValue: smLists['pestsAroundYesNoValue'],
              pestDescription: smLists['pestDescription'],
              signsDiseaseYesNoValue: smLists['signsDiseaseYesNoValue'],
              diseaseDescription: smLists['diseaseDescription'],
              fertiliserAppliedYesNoValue:
                  smLists['fertiliserAppliedYesNoValue'],
              fertiliserType: smLists['fertiliserType'],
              pesticideHerbicideAppliedYesNoValue:
                  smLists['pesticideHerbicideAppliedYesNoValue'],
              pesticideHerbicideType: smLists['pesticideHerbicideType'],
              additionalObservations: smLists['additionalObservations'],
              conStat: smLists['conStat'],
            ))
        .toList();
    notifyListeners();
  }
}
